version: '3.8'

services:
  service_1:
    image: service_1  # Используем уже собранный образ
    deploy:
      replicas: 2
    ports:
      - "8080:8080"
    depends_on:
      - service_2

  service_2:
    image: service_2  # Используем уже собранный образ
    deploy:
      replicas: 2
    ports:
      - "8081:8081"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    deploy:
      replicas: 1
    depends_on:
      - service_1
      - service_2
